# Use root/example as user/password credentials
version: '3.9'

services:
  db:
    container_name: imsim.io.mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MARIADB_USER: $DB__USER
      MARIADB_PASSWORD: $DB__PASSWORD
      MARIADB_DATABASE: $DB__NAME
    ports:
      - "${DB__PORT}:${DB__PORT}"
    volumes:
      - $VOLUMES_DIR/mariadb_data:/var/lib/mysql
    networks:
      - imsim.io

  adminer:
    container_name: imsim.io.adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - imsim.io

networks:
  imsim.io:
    external: true
